[package]
edition = "2021"
name = "woptipng"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.17", features = ["derive"]}
humansize = "1.1.1"
image = "0.24.2"
rayon = "1.5.2"
walkdir = "2.3.2"
